# wiki用ブランチの変更をGitHub Wikiに反映する
language: bash

branches:
  only: /^wiki\/.*$/

script:
  - git remote add wiki-repo github.com:$TRAVIS_REPO_SLUG.wiki &&
    git remote add code-repo github.com:$TRAVIS_REPO_SLUG &&
    git config --global user.email "$(git show -s --format='%an')" &&
    git config --global user.name "$(git show -s --format='%ae')"

  # 1. wiki-repoから既存の変更を取り込む（衝突した場合はビルド失敗）
  - git pull --rebase wiki-repo master || exit 1

  # 2. wiki-repoに新しい変更を反映し、
  # 3. code-repoのwiki用ブランチに変更を同期する（force push）
  - if [[ "$TRAVIS_BRANCH" == "wiki/master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      git push wiki-repo HEAD:master;
      git push --force code-repo HEAD:wiki/master;
    fi
