language: bash

script:
  # Wikiから既存の変更を取り込む
  - git config --global user.email "you@example.com" &&
    git config --global user.name "Your Name" &&
    git pull --rebase $WIKI_REPO master

  # Wikiに新しい変更を反映する
  - git push $WIKI_REPO $TRAVIS_BRANCH:master

  # リポジトリのwikiブランチに同期しておく
  - git push $CODE_REPO $TRAVIS_BRANCH:wiki

env:
  global:
    CODE_REPO=github.com:$TRAVIS_REPO_SLUG
    WIKI_REPO=github.com:$TRAVIS_REPO_SLUG.wiki
