# wiki用ブランチの変更をGitHub Wikiに反映する
language: bash

branches:
  only: /^wiki\/.*$/

env:
  global:
    CODE_REPO=github.com:$TRAVIS_REPO_SLUG
    WIKI_REPO=github.com:$TRAVIS_REPO_SLUG.wiki

script:
  # 1. WIKI_REPOから既存の変更を取り込む（衝突した場合は強制終了）
  - git config --global user.email "you@example.com" &&
    git config --global user.name "Your Name" &&
    git pull --rebase $WIKI_REPO master ||
    exit 1

  # 2. WIKI_REPOに新しい変更を反映し、
  # 3. CODE_REPOのwiki用ブランチに変更を同期する（force push）
  - if [[ "$TRAVIS_BRANCH" == "wiki/master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      git push $WIKI_REPO HEAD:master;
      git push --force $CODE_REPO HEAD:wiki/master;
    fi

