# wiki用ブランチの変更をGitHub Wikiに反映する
language: bash

branches:
  only: /^wiki\/.*$/

env:
  global:
    CODE_REPO=github.com:$TRAVIS_REPO_SLUG
    WIKI_REPO=github.com:$TRAVIS_REPO_SLUG.wiki

script:
  - git config --global user.email "$(git show -s --format='%an')" &&
    git config --global user.name "$(git show -s --format='%ae')"

  - export PREV_DIR=$PWD
  - git clone $WIKI_REPO /tmp/wiki &&
    cd /tmp/wiki

  # 1. wiki-repoから既存の変更を取り込む（衝突した場合はビルド失敗）
  - git pull --rebase wiki-repo master || exit 1

  # 2. wiki-repoに新しい変更を反映し、
  # 3. code-repoのwiki用ブランチに変更を同期する（force push）
  - if [[ "$TRAVIS_BRANCH" == "wiki/master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      git push wiki_repo HEAD:master;
      git push --force code-repo HEAD:wiki/master;
    fi
