language: bash
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - git pull --rebase $WIKI_REPO master
  - git push $WIKI_REPO $TRAVIS_BRANCH:master -f
env:
  global:
    WIKI_REPO=github.com:$TRAVIS_REPO_SLUG.wiki
