# wiki用ブランチの変更をGitHub Wikiに反映する
language: bash

branches:
  only: /^wiki\/.*$/

env:
  global:
    CODE_REPO=github.com:$TRAVIS_REPO_SLUG
    WIKI_REPO=github.com:$TRAVIS_REPO_SLUG.wiki

script:
  # - git config --global user.email "you@example.com" &&
  #   git config --global user.name "Your Name"

  # 1. WIKI_REPOから既存の変更を取り込む（衝突した場合はビルド失敗）
  - git remote add wiki-repo $WIKI_REPO &&
    git fetch wiki-repo master &&
    git rebase --onto wiki-repo/master wiki/master HEAD || exit 1

  # 2. WIKI_REPOに新しい変更を反映し、
  # 3. CODE_REPOのwiki用ブランチに変更を同期する（force push）
  - if [[ "$TRAVIS_BRANCH" == "wiki/master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      git push wiki_repo HEAD:master;
      git push --force $CODE_REPO HEAD:wiki/master;
    fi
